sudo docker stop monitoring-container || true
sudo docker rm monitoring-container || true

sudo docker ps -q --filter "publish=80" | xargs -r sudo docker stop
sudo docker ps -aq --filter "publish=80" | xargs -r sudo docker rm
